service: omni-support-portal-api

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'devint'}
  memorySize: 128 
  timeout: 15
  environment:
    stage: ${self:provider.stage}}
  # iam: 
  #   role: arn:aws:iam::083868342691:role/omni-support-portal-api-devint-us-east-1-lambdaRole
  #   deploymentRole: arn:aws:iam::083868342691:role/omni-support-portal-api-devint-us-east-1-lambdaRole

custom:
  prune:
    automatic: true
    number: 3
  jest:
    collectCoverage: true

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - 'node_modules/**'
    - 'src/**'
    - '*.*'
    - 'config/**'
    - '__tests__/**'
    - 'coverage/**'
    - 'Jenkinsfile'

functions:

    - ${file(config/CustomerOnboarding/deleteCustomer.yml)}
    - ${file(config/CustomerOnboarding/getCustomersList.yml)} 
    - ${file(config/CustomerOnboarding/postCustomer.yml)}
    - ${file(config/CustomerOnboarding/updateCustomer.yml)}
    - ${file(config/CustomerOnboarding/customersSummary.yml)}    
    - ${file(config/CustomerOnboarding/searchCustomer.yml)}
    - ${file(config/CustomerOnboarding/getActiveCustomersList.yml)}    

    - ${file(config/KeyManagement/postKey.yml)}    
    - ${file(config/KeyManagement/updateKey.yml)}

    - ${file(config/Subscription/deleteSubscription.yml)}
    - ${file(config/Subscription/getSubscriptionsList.yml)}
    - ${file(config/Subscription/postSubscription.yml)}
    - ${file(config/Subscription/updateSubscription.yml)}
    - ${file(config/Subscription/getEventTypesList.yml)}
    - ${file(config/Subscription/deleteWebhooks.yml)}    

    - ${file(config/UserActivity/allUsersActivityList.yml)}
    - ${file(config/UserActivity/getUserActivityList.yml)}    
    - ${file(config/UserActivity/postUserActivity.yml)}

plugins:
  - serverless-jest-plugin
  - serverless-offline
  - serverless-prune-plugin

layers:
  commonLibs:
    path: lib
    compatibleRuntimes:
      - nodejs14.x
    package:      
      include:
        - node_modules/**
