AllUsersActivityList:
  handler: src/UserActivity/AllUsersActivityList/index.handler
  role: arn:aws:iam::083868342691:role/omni-support-portal-api-devint-us-east-1-lambdaRole
  layers:
    - { Ref: CommonLibsLambdaLayer }
  environment:
    USER_ACTIVITY: ${ssm:/omni/${self:provider.stage}/support/portal/useractivity/table/name}
    DEFAULT_AWS: ${self:provider.region}    
  package:
    individually: true
    include:
        - 'src/UserActivity/AllUsersActivityList/**'
        - 'src/shared/**'    
  events:
    - http:
        path: /activity
        method: get
        cors: true
