PostUserActivity:
  handler: src/UserActivity/PostUserActivity/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }
  package:
    individually: true
    include:
        - 'src/UserActivity/PostUserActivity/**'
        - 'src/shared/**'    
  events:
    - http:
        path: /activity/{id}
        method: post
        cors: true
