GetUserActivityList:
      handler: src/UserActivity/GetUserActivityList/api/index.handler
      events:
        - http:
            path: /activity/{id}
            method: get
            cors: true
