GetEventTypesList:
  handler: src/Subscription/GetEventTypesList/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }  
  environment:
    EVENT_TOPIC_TABLE: ${ssm:/omni/devint/eventing/topics/table/name}
    TOKEN_VALIDATOR_TABLE: ${ssm:/omni-dw/devint/tokenValidator/table}
    DEFAULT_AWS: ${self:provider.region} 
  package:
    individually: true
    include:
        - 'src/Subscription/GetEventTypesList/**'
        - 'src/shared/**'
  events:
    - http:
        path: events
        method: get
        cors: true
