GetSubscriptionsList:
  handler: src/Subscription/GetSubscriptionsList/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }
  events:
    - http:
        path: subscriptions
        method: get
        cors: true
