GetSubscriptionsList:
  handler: src/Subscription/GetSubscriptionsList/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }
  package:
    individually: true
    include:
        - 'src/Subscription/GetSubscriptionsList/**'
        - 'src/shared/**'    
  events:
    - http:
        path: subscriptions
        method: get
        cors: true
