PostSubscription:
  handler: src/Subscription/PostSubscriptions/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }
  events:
    - http:
        path: subscriptions
        method: post
        cors: true
