PostSubscription:
  handler: src/Subscription/PostSubscriptions/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }
  environment:
    ACCOUNT_INFO: ${ssm:/omni/${self:provider.stage}/account/info/table/dev/name}
    TOKEN_VALIDATOR: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    CUSTOMER_PREFERENCE_TABLE: ${ssm:/omni/${self:provider.stage}/eventing/preferences/table/name}
    EVENTING_TOPICS_TABLE: ${ssm:/omni/${self:provider.stage}/eventing/topics/table/name}
    USAGE_PLAN: ${ssm:/omni/${self:provider.stage}/usage/plan/name}
    DEFAULT_AWS: ${self:provider.region}
  package:
    individually: true
    include:
      - "src/Subscription/PostSubscriptions/**"
      - "src/shared/**"
  events:
    - http:
        path: subscriptions
        method: post
        cors: true
