UpdateSubscription:
  handler: src/Subscription/UpdateSubscription/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }
  environment:
    TOKEN_VALIDATOR: ${ssm:/omni-dw/devint/tokenValidator/table}
    CUSTOMER_PREFERENCE_TABLE: ${ssm:/omni/devint/eventing/preferences/table/name} 
    EVENTING_TOPICS_TABLE: ${ssm:/omni/devint/eventing/topics/table/name}   
    DEFAULT_AWS: ${self:provider.region}    
  package:
    individually: true
    include:
        - 'src/Subscription/UpdateSubscription/**'
        - 'src/shared/**'    
  events:
    - http:
        path: subscriptions
        method: put
        cors: true
