PostKey:
  handler: src/KeyManagement/PostKey/index.handler
  role: arn:aws:iam::083868342691:role/omni-support-portal-api-devint-us-east-1-lambdaRole
  layers:
    - { Ref: CommonLibsLambdaLayer }
  environment:
    TOKEN_VALIDATOR: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    USAGE_PLAN: ${ssm:/omni-dw/${self:provider.stage}/usage/plan/id}
    DEFAULT_AWS: ${self:provider.region}       
  package:
    individually: true
    include:
        - 'src/KeyManagement/PostKey/**'
        - 'src/shared/**'    
  events:
    - http:
        path: keys
        method: post
        cors: true
