UpdateKey:
  handler: src/KeyManagement/UpdateKey/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer } 
  package:
    individually: true
    include:
        - 'src/KeyManagement/UpdateKey/**'
        - 'src/shared/**'     
  events:
    - http:
        path: keys
        method: put
        cors: true