DeleteSubscription:
      handler: src/Subscription/DeleteSubscription/api/index.handler
      events:
        - http:
            path: subscriptions
            method: delete
            cors: true
