GetSubscriptionsList:
      handler: src/Subscription/GetSubscriptionsList/api/index.handler
      events:
        - http:
            path: subscriptions
            method: get
            cors: true
