DeleteCustomer:
  handler: src/CustomerOnboarding/DeleteCustomer/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }
  environment:
    ACCOUNT_INFO: ${ssm:/omni/devint/account/info/table/dev/name}
    TOKEN_VALIDATOR: ${ssm:/omni/devint/token/validator/table/name}
    DEFAULT_AWS: ${self:provider.region}     
  package:
    individually: true
    include:
        - 'src/CustomerOnboarding/DeleteCustomer/**'
        - 'src/shared/**'    
  events:
    - http:
        path: customers
        method: delete
        cors: true            
