GetCustomersList:
  handler: src/CustomerOnboarding/GetCustomersList/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }  
  environment:
    accountInfo: ${ssm:/omni/devint/account/info/table/name}
    tokenValidator: ${ssm:/omni/devint/account/info/table/name}        
  events:
    - http:
        path: customers
        method: get
        cors: true
            