GetCustomersList:
  handler: src/CustomerOnboarding/GetCustomersList/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }  
  environment:
    ACCOUNT_INFO: ${ssm:/omni/devint/account/info/table/name}
    TOKEN_VALIDATOR: ${ssm:/omni/devint/account/info/table/name} 
  package:
    individually: true
    include:
        - 'src/CustomerOnboarding/GetCustomersList/**'
        - 'src/shared/**'
  events:
    - http:
        path: customers
        method: get
        cors: true
            