GetCustomersList:
  handler: src/CustomerOnboarding/GetCustomersList/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }  
  events:
    - http:
        path: customers
        method: get
        cors: true
            