GetCustomersList:
  handler: src/CustomerOnboarding/GetCustomersList/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }  
  environment:
    ACCOUNT_INFO: ${ssm:/omni/devint/account/info/table/name}
    TOKEN_VALIDATOR: ${ssm:/omni/devint/account/info/table/name} 
  package:
    include:
      - src/CustomerOnboarding/GetCustomersList/**  
      - src/shared/**
    exclude: 
      - node_modules/**
      - config/**
  events:
    - http:
        path: customers
        method: get
        cors: true
            