PostCustomer:
  handler: src/CustomerOnboarding/PostCustomer/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }  
  environment:
    ACCOUNT_INFO: ${ssm:/omni/${self:provider.stage}/account/info/table/dev/name}
    TOKEN_VALIDATOR: ${ssm:/omni-dw/${self:provider.stage}/tokenValidator/table}
    USAGE_PLAN: ${ssm:/omni/${self:provider.stage}/usage/plan/name}
    DEFAULT_AWS: ${self:provider.region} 
  package:
    individually: true
    include:
      - 'src/CustomerOnboarding/PostCustomer/**'
      - 'src/shared/**'
  events:
    - http:
        path: customers
        method: post
        cors: true
