UpdateCustomer:
  handler: src/CustomerOnboarding/UpdateCustomer/index.handler
  role: arn:aws:iam::083868342691:role/omni-support-portal-api-devint-us-east-1-lambdaRole  
  layers:
    - { Ref: CommonLibsLambdaLayer }
  environment:
    ACCOUNT_INFO: ${ssm:/omni-dw/${self:provider.stage}/accountInfo/table}
    DEFAULT_AWS: ${self:provider.region}     
  package:
    individually: true
    include:
        - 'src/CustomerOnboarding/UpdateCustomer/**'
        - 'src/shared/**'      
  events:
    - http:
        path: customers
        method: put
        cors: true
